services:
  - type: web
    name: pronet-simulacion
    env: static
    buildCommand: echo "Usando compilación estática incluida en el repositorio"
    staticPublishPath: ./artifacts/pronet-testing-simulation/dist/public
    autoDeploy: true